# config.yaml
rotary:
  enable_pin: 18
  count_pin: 23
  bounce_time: 10
  debounce_delay: 0.01

hook:
  pin: 22
  sound_file: 'sounds/on_hook.mp3'

sounds:
  greeting: 'sounds/greeting.wav'
  leave_message: 'sounds/leave_a_message.wav'

audio_output:
  device_address: 'hw:1,0'  # Change this to your desired audio output device address

recording:
  max_duration: 30  # Maximum duration in seconds

telegram:
  token: "TELEGRAM_TOKEN"
  chat_id: "TELEGRAM_CHAT_ID"

blagues-api:
  token: blagues-api-token

led:
  enabled: True
  pin: 21  # GPIO pin connected to the LED
  num_leds: 1  # Number of LEDs
  brightness: 127  # Brightness of the LED
